apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp-ergonomics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sampleapp
      version: ergonomics
  template:
    metadata:
      labels:
        app: sampleapp
        version: ergonomics
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: sampleapp-ergonomics
        image: aksjvmlabacr.azurecr.io/sampleapp:latest
        imagePullPolicy: Always
        env:
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          value: "InstrumentationKey=1020171d-042f-4fce-b2a5-271f0179ace3;IngestionEndpoint=https://westus2-2.in.applicationinsights.azure.com/;LiveEndpoint=https://westus2.livediagnostics.monitor.azure.com/"
        - name: APPLICATIONINSIGHTS_ROLE_NAME
          value: "Ergonomics"
        - name: APPLICATIONINSIGHTS_PREVIEW_PROFILER_ENABLED
          value: "true"
        - name: JAVA_OPTS
          value: "-XX:+UseParallelGC -XX:MaxRAMPercentage=70"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: "3000m"
            memory: "3Gi"
          limits:
            cpu: "3000m"
            memory: "3Gi"
# Spring Boot tuning example
# -Dspring.task.execution.pool.max-size=128 -Dspring.task.execution.pool.queue-capacity=50 -Dspring.task.execution.pool.keep-alive=10s"
---
apiVersion: v1
kind: Service
metadata:
  name: internal-sampleapp-ergonomics
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    targetPort: 8080
  selector:
    app: sampleapp
    version: ergonomics
