apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp-3by2
spec:
  strategy: 
    type: Recreate
  replicas: 3
  selector:
    matchLabels:
      app: sampleapp
      version: 3by2
  template:
    metadata:
      labels:
        app: sampleapp
        version: 3by2
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: sampleapp-3by2
        image: techxchange2025acr.azurecr.io/sampleapp:latest
        imagePullPolicy: Always
        env:
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          valueFrom:
            configMapKeyRef:
              name: app-insights-config
              key: connection-string
        - name: APPLICATIONINSIGHTS_ROLE_NAME
          value: "3BY2"
        - name: APPLICATIONINSIGHTS_PREVIEW_PROFILER_ENABLED
          value: "true"
        - name: JDK_JAVA_OPTIONS
          value: "-XX:MaxRAMPercentage=70 -XX:+UseParallelGC"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: "2000m"
            memory: "2Gi"
          limits:
            cpu: "2000m"
            memory: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: internal-sampleapp-3by2
  labels: 
    service: sampleappfront
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  selector:
    app: sampleapp
    version: 3by2